#!/bin/sh
set -eu
EXEC_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"

/usr/bin/osascript <<OSA
tell application "Terminal"
    activate
    do script quoted form of POSIX path of "${EXEC_DIR}/run-set.command"
    delay 0.2
    set bounds of front window to {120, 80, 1320, 870}
end tell
OSA
